### ISSUE TITLE
error:java.sql.SQLSyntaxErrorException: Table 'flinksql.AreaCnts' doesn't exist.

### ISSUE THREAD

**Issue by Lswx2017** [ververica/sql-training#12] opened 2020-05-27 03:24 UTC
When sink data to External Tables, i got error:java.sql.SQLSyntaxErrorException: Table 'flinksql.AreaCnts' doesn't exist.
I  just follow the tutorial: https://github.com/ververica/sql-training/wiki/Ecosystem-and-Writing-to-External-Tables#maintaining-a-continuously-updated-materialized-view-in-mysql
Did it need to create table in mysql by myself?

**Comment by fhueske** [comment] 2020-06-19 10:23
Thanks for reporting this issue and sorry for the late response @Lswx2017 

The `AreaCnts` table should be automatically created when the MySQL image is started. 
The docker-compose scripts mounts the local `mysql` folder which contains the script to create the table to the path `/docker-entrypoint-initdb.d` in the MySQL container which runs the scripts in the folder after the DB started.
So everything should be completely setup.

I'll close this issue as I couldn't reproduce the problem. 
Please try again and reopen the issue if it still fails for you.

Thank you, Fabian

**Closed as completed by fhueske** 2020-06-19 10:23 UTC
