### ISSUE TITLE
Jackson issue when selecting data from table

### ISSUE THREAD

**Issue by ghost** [ververica/sql-training#8] opened 2020-02-12 17:05 UTC
Hello,

There is an issue with the docker image as it's not working out of the box.
When running the SQL CLI and trying to 'select * from Rides' I get an error:
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassCastException: cannot assign instance of java.util.concurrent.ConcurrentHashMap to field org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.DeserializerCache._cachedDeserializers of type org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.util.LRUMap in instance of org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.DeserializerCache

**Comment by zhch158** [comment] 2020-02-17 11:41
me too!

**Comment by sskhiri** [comment] 2020-02-25 13:03
I have the same for all queries. 
The complete log for 3 queries is here [log.txt](https://github.com/ververica/sql-training/files/4250285/log.txt).

**Comment by sskhiri** [comment] 2020-02-25 15:49
@fhueske 
The issue comes from the update to Flink 1.9. If we checkout an earlier version in the commit log, the problem is not there anymore. I checked out this commit (just right before the commit that updated in Flink 1.9):

commit 098bf1d11e87c8af9787c896d9672bfb0fe8f532
Author: Fabian Hueske <fhueske@apache.org>
Date:   Thu Apr 11 17:22:28 2019 +0200

    Add build environment for sql client docker image

As a result a simple git checkout 098bf1d11e87c8af9787c896d9672bfb0fe8f532 allows to temporary work with the tutorial (but on Flink 1.7).

**Comment by fhueske** [comment] 2020-02-25 16:54
Hi everyone, sorry not replying earlier!
I just became aware of this issue now.

I haven't had a closer look, but this is quite strange because I've used this version before without any issues. Maybe it was caused by the release of Flink 1.10.
Anyway, I'm going to update the training to Flink 1.10 in the next days to be prepared for the training at Flink Forward SF.

@sskhiri , thanks for pinging me and your investigation!

Thanks, Fabian

**Comment by fhueske** [comment] 2020-02-25 17:05
Alright, I found the issue.
The problem is that Flink 1.9.2 (which was released a few weeks ago) doesn't seem to be compatible with Flink 1.9.0. 
The `docker-compose.yml` file pulls in the latest version of the Flink 1.9 release line (Flink 1.9.2 by now) which does not work with the custom `sql-client` image which is based on Flink 1.9.0.

The easiest way to fix this is to fix the Flink version in `docker-compose.yml` to Flink 1.9.0 by replacing `image: flink:1.9-scala_2.11` with `image: flink:1.9.0-scala_2.11` (for JobManager and TaskManager).

**Comment by fhueske** [comment] 2020-02-25 17:11
I pushed a commit to fix the issue. 
I'll close this issue. Please reopen if the fix doesn't work for you.

Thanks, Fabian

**Closed as completed by fhueske** 2020-02-25 17:11 UTC

**Comment by sskhiri** [comment] 2020-02-25 18:30
@fhueske your commit works, there is no error anymore. However, it seems that now there is no event received. A simple select * from Rides; does not generate any error anymore but not does not give any result. It is like no event are sent to Flink.

**Comment by sskhiri** [comment] 2020-02-25 19:06
OK, my mistake, it was due to images that were not cleaned. A "
docker system prune" cleaned everything. Your fix works perfectly !

**Comment by fhueske** [comment] 2020-02-25 19:35
Thanks for the feedback!

**Comment by zhch158** [comment] 2020-02-28 10:14
thank you!



郑春
 
From: Sabri Skhiri
Date: 2020-02-26 03:06
To: ververica/sql-training
CC: zhch158; Comment
Subject: Re: [ververica/sql-training] Jackson issue when selecting data from table (#8)
OK, my mistake, it was due to images that were not cleaned. A "
docker system prune" cleaned everything. Your fix works perfectly !
